config/routes.rb
Passit::Application.routes.draw do
  get "resources/show"
  root to: 'static_pages#home' # establece como pagina de inicio static_pages#home
  match '' => 'static_pages#home', via: [:get, :post]
  match 'ayuda' => 'static_pages#help', via: [:get, :post]
  match 'nosotros' => 'static_pages#about', via: [:get, :post]

  get 'static_pages/home' => 'static_pages#home'
  get 'static_pages/about' => 'static_pages#about'
  get 'static_pages/help' => 'static_pages#help'
  resources :categories
  resources :resources

end

app/models/category.rb
class Category < ActiveRecord::Base
	before_save { self.name = name.downcase } # name a minusculas para asegurar la singularidad de nombres
	validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
	has_many :resources
end

app/models/resource.rb
class Resource < ActiveRecord::Base
	validates :name, presence: true, length: { maximum: 50 }, uniqueness: { case_sensitive: false }
	validates :url, presence: true
	validates :category_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate, :except => [:index, :show] # no pedir authenticate para show y index

  def new
  	@category = Category.new
  end

  def create
  	@category = Category.new(user_params)   
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end

  def show
  	@category = Category.find(params[:id])
  end

  def index
    @categories = Category.all
  end

  protected
    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == 'admin' && password == 'admin' # simpel authentication
      end
    end

    def user_params
      params.require(:category).permit(:name)
    end

end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
	before_filter :authenticate, :except => [:show] # no pedir authenticate para show y index

  def new
    @resource = Resource.new
  end

  def create
    @resource = Resource.new(user_params)   
    if @resource.save
      redirect_to @resource
    else
      render 'new'
    end
  end

  def show
  	@resource = Resource.find(params[:id])
  end

  protected
    def authenticate
      authenticate_or_request_with_http_basic do |username, password|
        username == 'admin' && password == 'admin' # simple authentication
      end
    end

    def user_params
      params.require(:resource).permit(:name, :url, :category_id, :pdf)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# De vuelve el título completo rellenando con el de cada pagina
  def full_title(page_title)
    base_title = "#YoSoyEDU"
    if page_title.empty? # si no hay tituo en la pagina solo se pone el base
      base_title
    else
      "#{page_title} - #{base_title}" # titulo de la pagina - hashtag
    end
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/_error_messages.html.erb
<% if @category.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(@category.errors.count, "error") %>.
    </div>
    <ul>
    <% @category.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/categories/index.html.erb
<% provide(:title, 'Categorías') %>
<!--panel principal!-->
<td id="panel">

	<h1>Todas las Categorías</h1>

	<h3>Selecciona sobre qué categoría estas buscando recursos</h3>

	<% @categories.each do |cat| %>
		<div class="view view-first">  
    	<%= image_tag "categories/"+cat.img %>  
	    	<div class="mask">  
	    	<h2><%= cat.name %></h2>  
	    	<p><%= cat.s_desc %></p>  
	        <%= link_to 'Más', cat , class: 'info' %>  
	     	</div>  
		</div>  	
	<% end %>

</td>

	<%= render 'layouts/espaciador' %>
		
<!--panel derecho!-->
<td id="rightpanel">
	<%= image_tag("nos.png", size: "150x99", style: "float:right;margin-left:20px") %>
	<p>Hola, somos Adrián y Fran, dos estudiantes de Ingeniería de Software. Nuestro mayor interés es que podamos aprender todos juntos, y que formemos una gran comunidad. Así que ya sabéis chicos, nosotros podemos aprobar porque #YoSoyEDU</p>

	<%= render 'layouts/calendar' %>
</td>

app/views/categories/new.html.erb
<% provide(:title, 'Nueva Categoría') %>
<!--panel principal!-->
<td id="panel">

	<h1>Nueva Categoría</h1>

	 <%= form_for(@category) do |f| %>

	  <%= render 'error_messages' %>

      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name %>

      <%= f.submit "Crear categoría" %>
    <% end %>

</td>

	<%= render 'layouts/espaciador' %>
		
<!--panel derecho!-->
<td id="rightpanel">
	<%= image_tag("nos.png", size: "150x99", style: "float:right;margin-left:20px") %>
	<p>Hola, somos Adrián y Fran, dos estudiantes de Ingeniería de Software. Nuestro mayor interés es que podamos aprender todos juntos, y que formemos una gran comunidad. Así que ya sabéis chicos, nosotros podemos aprobar porque #YoSoyEDU</p>
				
	<%= render 'layouts/calendar' %>
</td>

app/views/categories/show.html.erb
<% provide(:title, @category.name.capitalize) %>
<!--panel principal!-->
<td id="panel">

 	<h1>Recursos de <%= @category.name.capitalize %></h1>

 	<p>Selecciona el recurso que quieres visitar, si algún enlace esta roto no dudes en escribirnos a passitedu[at]gmail.com</p>

 	<% @category.resources.each do |res| %>
 		<div style="width:200px;height:150px;" class="view view-first">
 			<h3><%= res.name %></h3>
 			<%= link_to 'Acceder', res , class: "info"%> 
 		</div>
 	<% end %>

</td>

	<%= render 'layouts/espaciador' %>
		
<!--panel derecho!-->
<td id="rightpanel">
	<%= image_tag("nos.png", size: "150x99", style: "float:right;margin-left:20px") %>
	<p>Hola, somos Adrián y Fran, dos estudiantes de Ingeniería de Software. Nuestro mayor interés es que podamos aprender todos juntos, y que formemos una gran comunidad. Así que ya sabéis chicos, nosotros podemos aprobar porque #YoSoyEDU</p>
				

	<%= render 'layouts/calendar' %>
</td>

app/views/layouts/_calendar.html.erb
<div style="margin-top:20px;"><iframe src="https://www.google.com/calendar/embed?title=Calendario%20de%20Directos&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;height=270&amp;wkst=2&amp;hl=es&amp;bgcolor=%2333cc00&amp;src=passitedu%40gmail.com&amp;color=%232952A3&amp;ctz=Europe%2FMadrid" style=" border-width:0 " width="300" height="270" frameborder="0" scrolling="no"></iframe></div>

app/views/layouts/_creative.html.erb
<div style="font-size:12px;margin-top:20px;">
	<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><center><img alt="Licencia de Creative Commons" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a></center>
	<br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">PassItEDU</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://www.passitedu.es" property="cc:attributionName" rel="cc:attributionURL">Adrián & Fran</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Reconocimiento-NoComercial-CompartirIgual 4.0 Internacional License</a>.<br />
</div>

app/views/layouts/_espaciador.html.erb
<td style="padding:0px;;vertical-align:bottom;width:20px;"><div style="position:relative;bottom:-0.5px;" class="square"></div></td> <!--espaciador entre paneles!-->

app/views/layouts/_footer.html.erb
<td style="padding:0px;vertical-align:bottom;"><div style="position:relative;bottom:-16px;left:-16px;-webkit-transform: rotate(-45deg);-moz-transform: rotate(-45deg);" class="triangle"></div></td><!--triang der!-->
		</table>

		<div style="margin:0 auto 0 auto;" id="footer">
			<!--footer!-->
			<table style="margin:0 auto 0 auto;padding:0;">
				<td style="vertical-align:top;">
					<h4 style="margin:0;padding:0;"><b>Contacto</b></h4>
					<ul>
						<li><%= link_to "Youtube" , 'http://www.youtube.com/passitEDU', :target => "_blank" %></li>
						<li><%= link_to "Facebook" , 'http://www.facebook.com/passitEDU', :target => "_blank" %></li>
						<li><%= link_to "Twitterk" , 'http://www.twitter.com/passitEDU', :target => "_blank" %></li>
						<li>contacto[at]passitedu.es</li>
					</ul>
				</td>
				<td style="vertical-align:top;">
					<h4 style="margin:0;padding:0;"><b>Enlaces de Interes</b></h4>
					<ul>
						<li><%= link_to "¿Quiénes Somos?" , 'nosotros' %></li>
						<li><%= link_to "Foro de dudas" , 'http://www.passitedu.es/campusvirtual', :target => "_blank" %></li>
					</ul>
				</td>
				<td style="vertical-align:top;">
					<h4 style="margin:0;padding:0;"><b>Web Amigas</b></h4>
					<ul>
						<li><%= link_to "InfoVap" , 'http://www.infovap.es', :target => "_blank" %></li>
						<li><%= link_to "Mediaware" , 'http://www.mediaware.tk', :target => "_blank" %></li>
						<li><%= link_to "SomosBinarios" , 'http://www.somosbinarios.es/', :target => "_blank" %></li>
					</ul>
				</td>
				<td style="vertical-align:top;margin:0px;padding:0;" width="400">
					<p style="font-size:14px;margin:20px 0px 0px 20px;">Si quiere colaborar con el mantenimiento de la web, puedes aportar una donación a través de paypal con la cantidad que considere oportuna. Muchas Gracias.</div><div style="float:right;"><form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
					<input type="hidden" name="cmd" value="_s-xclick">
					<input type="hidden" name="hosted_button_id" value="RQZHCRBRALC2L">
					<input type="image" src="https://www.paypalobjects.com/es_ES/ES/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal. La forma rápida y segura de pagar en Internet.">
					<img alt="" border="0" src="https://www.paypalobjects.com/es_ES/i/scr/pixel.gif" width="1" height="1">
					</form></p>
				</td>			
			</table>
		</div>		
		<a href="#"><div class="fixedButton" title="Arriba"><div style="top:-8px;" class="arrow"></div></div></a><!--boton volver arriba!-->

app/views/layouts/_header.html.erb
<script>(function(d, s, id) { 
		  var js, fjs = d.getElementsByTagName(s)[0];
		  if (d.getElementById(id)) return;
		  js = d.createElement(s); js.id = id;
		  js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1&appId=345503222253641";
		  fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));</script><!-- script para el boton de facebook!-->
		
	<div class="fixedDiv">
		<div style="position:fixed;background-color:#644d3e;width:100%;height:5px;"></div>
		<!--menu social!-->
		<table style="magin:0 auto 0 auto;">
			<td style="margin:0;font-weight:bold;" class="nolink"><a style="color:#1b6c95;" href="http://www.passitedu.es">PassItEDU.ES</a></td>
			<td style="margin:0;width:380px;">Comparte este post <!--botones compartir!-->
				<div style="float:right;"><a href="https://twitter.com/share" class="twitter-share-button" data-via="PassItEDU" data-lang="es" data-hashtags="YoSoyEDU" data-dnt="true">Twittear</a>
				<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></div>
				<div style="float:right;" class="fb-share-button" data-href="http://www.passitedu.es" data-type="button_count"></div>
			</td>
			<td style="width:30%;padding:0;margin:0;"><!--buscador!-->
					<script> 
					  (function() {
					    var cx = '010586346072304361388:juelkdm0kbs';
					    var gcse = document.createElement('script');
					    gcse.type = 'text/javascript';
					    gcse.async = true;
					    gcse.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') +
					        '//www.google.com/cse/cse.js?cx=' + cx;
					    var s = document.getElementsByTagName('script')[0];
					    s.parentNode.insertBefore(gcse, s);
					  })();
					</script>
					<gcse:searchbox-only></gcse:searchbox-only>
			</td>
		</table>
	</div>

	<table id="menu">
		<div style="position:fixed;background-color:#644d3e;width:100%;height:5px;z-index:1000;"></div> <!-- barra marron!-->
		<tr>
			<td rowspan="2" style="padding:0px;"><%= link_to image_tag("passitlapiz.png", size: "285x80"), root_path %>
			</td> <!-- logo !-->

			<!--menu!-->
			<td style="width:100%;padding:0px;">
				<ul id="nav">
				<li><%= link_to "Recursos", categories_path %></li>
				<li><%= link_to "GNU/Linux", '#', class: 'submenu' %>
					<ul>
						<li><%= link_to "Shell de Linux", '#' %></li>				
					</ul>
				</li>
				<li><%= link_to "Herramientas", '#', class: 'submenu' %>
					<ul>
						<li><%= link_to "Conversor Unidades", '#' %></li>
						<li><%= link_to "Combinatoria", '#' %></li>
						<li><%= link_to "Binomio de Newton", '#' %></li>
						<li><a href="/es/tools/lista.php">Lista de vídeos</a></li>
					</ul>
				</li>
				<li><%= link_to "Diseño Web", '#', class: 'submenu' %>
					<ul>
						<li><%= link_to "HTML", '#' %></li>
						<li><%= link_to "CSS", '#' %></li>
						<li><%= link_to "HTML5", '#' %></li>
						<li><%= link_to "Crea un formulario", '#' %></li>
					</ul>
				</li>
				<li><%= link_to "Selectividad", '#' %></li>
				<li><%= link_to "Foro" , 'http://www.passitedu.foroactivo.com', :target => "_blank" %></li>
				</ul>
			</td>
		</tr>

		<tr>
			<td style="vertical-align:bottom;padding:0px;">
				<div class="socialButtons"><%= link_to image_tag("facebookw.png"), 'http://www.facebook.com/passitedu', :target => "_blank" %></div>
				<div class="socialButtons"><%= link_to image_tag("twitterw.png"), 'http://www.twitter.com/passitedu', :target => "_blank" %></div>
				<div class="socialButtons"><%= link_to image_tag("youtubew.png"), 'http://www.youtube.com/passitedu', :target => "_blank" %></div>
				<div class="socialButtons"><%= link_to image_tag("google+w.png"), 'http://www.plus.google.com/passitedu', :target => "_blank" %></div>
			</td>
		</tr>
	</table>

<!-- aqui ya comienza el cuerpo de la pagina !-->
<table style="margin:0 auto 0 auto;width:96.7%;border-spacing:0;">
<td style="padding:0px;vertical-align:bottom;"><div style="position:relative;bottom:-16px;right:-16px;-webkit-transform: rotate(-135deg);-moz-transform: rotate(-135deg);" class="triangle"></div></td><!--triang izq!-->

app/views/layouts/_shim.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,700,400' rel='stylesheet' type='text/css'><!--fuente de google!-->
<%= favicon_link_tag 'favIcon.ico' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
	<%= render 'layouts/header' %>

	<%= yield %>

	<%= render 'layouts/footer' %>
</body>
</html>

app/views/resources/_error_messages.html.erb
<% if @resource.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(@resource.errors.count, "error") %>.
    </div>
    <ul>
    <% @resource.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/resources/new.html.erb
<% provide(:title, 'Nuevo Recurso') %>
<!--panel principal!-->
<td id="panel">

	<h1>Nuevo Recurso</h1>

	<%= form_for(@resource) do |f| %>

	 <%= render 'error_messages' %>

      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name %>
      <br>
      <%= f.label :url, "Nombre del fichero.ext" %>
      <%= f.text_field :url %>
	  <br>
      <%= f.label :category_id, "Categoría" %>
      <%= f.text_field :category_id %>
      <br>
      <%= f.label :pdf, "¿Pdf?" %>
      <%= f.check_box :pdf %>
      <br>
      <%= f.submit "Crear recurso" %>
    <% end %>

</td>

	<%= render 'layouts/espaciador' %>
		
<!--panel derecho!-->
<td id="rightpanel">
	<%= image_tag("nos.png", size: "150x99", style: "float:right;margin-left:20px") %>
	<p>Hola, somos Adrián y Fran, dos estudiantes de Ingeniería de Software. Nuestro mayor interés es que podamos aprender todos juntos, y que formemos una gran comunidad. Así que ya sabéis chicos, nosotros podemos aprobar porque #YoSoyEDU</p>
				
	<%= render 'layouts/calendar' %>
</td>

app/views/resources/show.html.erb
<% provide(:title, @resource.name.capitalize) %>
<!--panel principal!-->
<td id="panel">

 	<h1><%= @resource.name.capitalize %></h1>

 	<% if @resource.pdf? == false %>	<!-- we check if its a pdf or not !-->
 		<%= render file: "/public/resources/"+@resource.url %> 
 	<% else %>
 		<embed src=<%= "/pdf/" + @resource.url %> width="750" height="800">
 	<% end %>

</td>

	<%= render 'layouts/espaciador' %>
		
<!--panel derecho!-->
<td id="rightpanel">
	<%= image_tag("nos.png", size: "150x99", style: "float:right;margin-left:20px") %>
	<p>Hola, somos Adrián y Fran, dos estudiantes de Ingeniería de Software. Nuestro mayor interés es que podamos aprender todos juntos, y que formemos una gran comunidad. Así que ya sabéis chicos, nosotros podemos aprobar porque #YoSoyEDU</p>
				

	<%= render 'layouts/calendar' %>
</td>

app/views/static_pages/about.html.erb
<% provide(:title, 'Sobre Nosotros') %>

<!--panel principal!-->
<td id="panel">

	<h3>Sobre Nosotros<h3>

 	<center>
 		<iframe width="640" height="360" src="http://www.youtube.com/embed/OwVWlsbjMd0?feature=player_detailpage" frameborder="0" allowfullscreen></iframe>
	<p> Buenas, somos <b>Adrián</b> y <b>Fran</b> y nosotros formamos <b>Pass-It</b>. Somos <b>dos estudiantes</b> de Ingeniería de Software en la Universidad de Málaga y por supuesto no somos matemáticos ni mucho menos. Nuestra <b>idea</b> es crear una comunidad sencilla en la que todos nos podamos <b>ayudar</b> a afrontar las dificultades que nos encontramos en nuestros estudios día a día. No solo intentamos ayudar con nuestros vídeos (que distan mucho de ser algo profesionales) sino que <b>intentamos</b> por todos los medios <b>crear una comunidad</b> donde todos nos ayudemos a todos. Porque nadie es experto en lo que sabe, empezando por <b>nosotros</b>, pero estamos seguro de que todos siempre podemos aportar un granito de arena. Espero que sea una buena experiencia, que os ayude, y que consigamos llegar lejos <b>todos juntos</b>. 
			<br></br>
	Un cordial saludo de Pass-It, de parte de Fran y Adrián.
	</center>

</td>

	<%= render 'layouts/espaciador' %>
		
<!--panel derecho!-->
<td id="rightpanel">
	<%= image_tag("nos.png", size: "150x99", style: "float:right;margin-left:20px") %>
	<p>Hola, somos Adrián y Fran, dos estudiantes de Ingeniería de Software. Nuestro mayor interés es que podamos aprender todos juntos, y que formemos una gran comunidad. Así que ya sabéis chicos, nosotros podemos aprobar porque #YoSoyEDU</p>
				

	<%= render 'layouts/calendar' %>			
</td>

app/views/static_pages/help.html.erb
<% provide(:title, 'Ayuda') %>
<h1>Ayuda</h1>
    <p>
      HOla k ase
    </p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Inicio') %>
<!--panel principal!-->
<td id="panel">

 	<h2>NUEVO - Disfruta de nuestros cursos !</h2>
	<center>
	<table style="text-align:center;margin-bottom:20px;">
		<thead>
			<tr>
				<th>Electrónica Digital</th>
				<th>Cálculo - Series Numéricas</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= link_to image_tag("elecDig.png"), "http://aula.tareasplus.com/PassIt-EDU/Electronica-Digital" %>
					<br>
					<ul>
						<li><a href="http://aula.tareasplus.com/PassIt-EDU/Electronica-Digital">13.99$ - 10.07€ - TareasPlus </a></li>
					</ul>
				</td>
				<td><%= link_to image_tag("calcSer.png"), "http://aula.tareasplus.com/PassIt-EDU/Calculo---Series-Numericas" %>
					<ul>
						<li><a href="http://aula.tareasplus.com/PassIt-EDU/Calculo---Series-Numericas">Gratis! - TareasPlus </a> / <a href="http://www.cursopedia.com/Ficha-Calculo---Series-Numericas">Cursopedia</a></li>
					</ul>
				</td>
			</tr>
		</tbody>
	</table>
		</center>

 		<b>Bienvenidos a la página web de Pass-It</b>:
		<br><br/>			

	 	<p>Tenemos más de 100 <a class="link" target="_new" href="http://youtube.com/PassItEdu"><b>videos de matemáticas</b></a> para resolver tus dudas, deseamos que Pass-it Edu te ayude en todo lo relacionado a tus estudios, siempre que tengas alguna duda, no dudes en contactar con nosotros mediante el <a class="link" target="_new" href="/campusvirtual"><b>foro</b></a>, <a class="link" target="_new"  href="http://youtube.com/PassItEdu"><b>Youtube</b></a>, <a class="link" target="_new"  href="http://twitter.com/PassItEdu"><b>Twitter</b></a>, <a class="link" target="_new"  href="http://facebook.com/PassItEdu"><b>Facebook</b></a> o mandándonos un correo (haz click en Contacto o mira al pie de página). Puedes estar al tanto de todas las novedades en nuestro <a class="link" target="_new" href="http://passitedu.blogspot.com/"><b>Blog</b></a>.
	 		<br></br>
		Ayudanos a crecer compartiendo Pass-it en las redes sociales y comentandonos a vuestros amigos. Para el mantenimiento de la web y del proyecto puedes donar una cantidad simbólica a través de Paypal, solo si lo crees oportuno.
	 		<br></br></p>		
			
 		<center>
 			<table style="margin:20px;">
	 			<td style="border-style:dotted;padding:10px;border-radius:5px;border: 1px solid #dedede;">
	 			Aquí puedes elegir lo que quieres hacer:
	 			<br></br>
	 			<%= link_to image_tag("youtubeB.png", class: "botonLight" , title: "Quiero ver vuestros vídeos!"), "http://www.youtube.com/PassItEdu", :target => "_blank" %>
	 			<%= link_to image_tag("foroB.png", class: "botonLight" , title: "Tengo dudas, llévame al foro!"), "/campusvirtual", :target => "_blank" %>
	 			<%= link_to image_tag("blogB.png", class: "botonLight" , title: "Quiero estar a la última en novedades!"), "http://passitedu.blogspot.com/", :target => "_blank" %>
		 		</td>
	 		</table></center>

		<p>Recuerda que tienes <b><a class="link" href="/es/recursos/">multitud de recursos</a></b> accesibles para que estudies, cuando lo necesites. 
					<br></br>
		También tenemos una nueva sección con <b><a class="link" href="/es/tools/">herramientas</a></b> como un conversor de bases, o un potente ayudante para cuando tengras que afrontar ejercicios de combinatoria.
					<br></br>
		Si buscas un vídeo sobre alguna categoría específica no dudes en pasarte por nuestro <b>buscador de vídeos</b>.
				<br></br>
		Y si lo tuyo es el <b><a class="link" href="/es/disenoWeb/">diseño web</a></b> y quieres aprender, por ejemplo, como esta hecha esta web, puedes pasarte por la sección y seguro que aprenderas un montón!
					<br></br>
		Muchas gracias y un saludo. El equipo de Pass-it</p>

		<%= render 'layouts/creative' %>

</td>

	<%= render 'layouts/espaciador' %>
		
<!--panel derecho!-->
<td id="rightpanel">
	<%= image_tag("nos.png", size: "150x99", style: "float:right;margin-left:20px") %>
	<p>Hola, somos Adrián y Fran, dos estudiantes de Ingeniería de Software. Nuestro mayor interés es que podamos aprender todos juntos, y que formemos una gran comunidad. Así que ya sabéis chicos, nosotros podemos aprobar porque #YoSoyEDU</p>
				
	<%= render 'layouts/calendar' %>
</td>

		